import { AssessmentResult } from "@/types/assessment";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Info, AlertTriangle, AlertCircle, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SignUpButton } from "@clerk/nextjs";
import Link from "next/link";

export function AssessmentResults({ result, isAnonymous }: { result: AssessmentResult; isAnonymous?: boolean }) {
  // Determine color coding based on severity string
  const severityColors: Record<string, string> = {
    minimal: "bg-green-50 text-green-900 border-green-200 dark:bg-green-950/30 dark:border-green-900 dark:text-green-200",
    mild: "bg-blue-50 text-blue-900 border-blue-200 dark:bg-blue-950/30 dark:border-blue-900 dark:text-blue-200",
    moderate: "bg-yellow-50 text-yellow-900 border-yellow-200 dark:bg-yellow-950/30 dark:border-yellow-900 dark:text-yellow-200",
    "moderately severe": "bg-orange-50 text-orange-900 border-orange-200 dark:bg-orange-950/30 dark:border-orange-900 dark:text-orange-200",
    severe: "bg-red-50 text-red-900 border-red-200 dark:bg-red-950/30 dark:border-red-900 dark:text-red-200",
  };

  const severityKey = result.severity.toLowerCase();
  const alertColor = severityColors[severityKey] || "bg-zinc-50 text-zinc-900 border-zinc-200 dark:bg-zinc-900 dark:border-zinc-800 dark:text-zinc-100";

  let Icon = Info;
  if (severityKey === "moderate" || severityKey === "moderately severe") Icon = AlertTriangle;
  if (severityKey === "severe") Icon = AlertCircle;

  return (
    <div className="w-full max-w-2xl mx-auto flex flex-col gap-6 px-4 py-8 sm:py-12">
      <Card className="border-zinc-200 dark:border-zinc-800 shadow-md">
        <CardHeader className="text-center pb-2">
          <CardTitle className="text-3xl font-bold tracking-tight">Assessment Complete</CardTitle>
          <CardDescription className="text-base mt-2">
            Your results have been securely generated by the LifeBack Assessment Engine.
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="flex flex-col items-center justify-center mb-8">
            <div className="text-sm font-medium text-zinc-500 uppercase tracking-wider mb-2">Total Score</div>
            <div className="text-6xl font-black text-zinc-900 dark:text-white">
              {result.totalScore}
            </div>
          </div>

          <Alert className={`mb-6 ${alertColor}`}>
            <Icon className="h-5 w-5" />
            <AlertTitle className="text-lg font-semibold ml-2">Result: {result.severity}</AlertTitle>
            <AlertDescription className="ml-2 mt-2 text-base leading-relaxed">
              {result.summary}
            </AlertDescription>
          </Alert>

          <p className="text-sm text-zinc-500 dark:text-zinc-400 text-center px-4">
            This is a standardized assessment result (Provider Version: {result.providerVersion}). 
            Please consult with a healthcare professional for a formal diagnosis.
          </p>
        </CardContent>
      </Card>

      {isAnonymous && (
        <Card className="border-indigo-100 bg-indigo-50/50 dark:border-indigo-900/50 dark:bg-indigo-950/20 shadow-sm mt-4">
          <CardHeader>
            <CardTitle className="text-xl text-indigo-900 dark:text-indigo-100">Save Your Progress</CardTitle>
            <CardDescription className="text-indigo-700/80 dark:text-indigo-300/80">
              Create a free account to securely store these results and unlock more features.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3 mb-6">
              {[
                "Keep your assessment history securely saved",
                "Track changes in your wellbeing over time",
                "Access future mental health assessments",
                "Continue right where you left off"
              ].map((benefit, i) => (
                <li key={i} className="flex items-start text-sm text-indigo-900/80 dark:text-indigo-200/80">
                  <CheckCircle2 className="h-5 w-5 mr-3 text-indigo-600 dark:text-indigo-400 shrink-0" />
                  <span>{benefit}</span>
                </li>
              ))}
            </ul>
            <div className="flex flex-col sm:flex-row gap-3">
              <SignUpButton mode="modal">
                <Button className="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm">
                  Create Free Account
                </Button>
              </SignUpButton>
              <Link href="/" className="w-full sm:w-auto">
                <Button variant="outline" className="w-full border-indigo-200 text-indigo-700 hover:bg-indigo-100 dark:border-indigo-800 dark:text-indigo-300 dark:hover:bg-indigo-900/50">
                  Maybe Later
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
